services:
  postgres:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  bot:
    image: ghcr.io/neumanf/vagastechrnbot-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres:
