version: '3.1'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: vagastechrnbot
      MYSQL_DATABASE: vagastechrnbot
      MYSQL_USER: vagastechrnbot
      MYSQL_PASSWORD: vagastechrnbot
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql