version: '3.1'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: vagastechrnbot
      MYSQL_DATABASE: vagastechrnbot
      MYSQL_USER: vagastechrnbot
      MYSQL_PASSWORD: vagastechrnbot
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  bot:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql: