services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: vagastechrnbot
      POSTGRES_USER: vagastechrnbot
      POSTGRES_PASSWORD: vagastechrnbot
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: