name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/neumanf/vagastechrnbot-bot:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy
        run: |
          cd $HOME/vagastechrnbot &&
          docker compose pull &&
          docker compose up --build -d

      - name: Run migrations
        run: docker exec vagastechrnbot-bot-1 /bin/sh -c "npm run migrate"
