name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: cp $HOME/envs/vagastechrnbot.env ./.env

      - name: Run Docker containers
        run: docker compose up -d
